port: "9090"

db:
  username: "postgres"
  # Раньше было так:
  # host:     "localhost"
  # port:     "5436"
  # Т.к. запускалось все локально. 

  # Теперь же вместо host:"localhost" host:"db" (название из docker compose)
  # С портом для БД сэйм

  host:     "db"
  port:     "5432"
  dbname:   "postgres"
  sslmode:  "disable"